version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    volumes:
      - ./user-service:/app

  workout-service:
    build: ./workout-service
    ports:
      - "8001:8001"
    volumes:
      - ./workout-service:/app
    depends_on:
      - user-service
